# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - build


image: google/cloud-sdk:latest
variables:
  PROVIDER: zekoder
  APP: zeauth  


build dev:
  stage: build
  variables:
    BRANCH: dev
    REGION: us-central1
    PROJECT: zekoder-dev-349809
    REGISTERY: us.gcr.io
  only:
    refs:
    - dev
  environment:
    name: dev
    url: https://zekoder.com/dev

  before_script:
  - echo $ZEKODER_SA > google-sa.json
  - ls
  - export GOOGLE_APPLICATIONS_CREDENTIALS=$PWD/google-sa.json
  - gcloud auth activate-service-account --key-file google-sa.json
  - gcloud auth configure-docker $REGISTERY
  - gcloud config set project $PROJECT
  - export APP_NAME=$PROVIDER-$APP-$BRANCH
  - export IMAGE_NAME=$REGISTERY/$PROJECT/$PROVIDER/$APP:$CI_COMMIT_SHORT_SHA

  - sed -i.bak -e "s+IMAGE+$IMAGE_NAME+" -e "s/SERVICE/$APP_NAME/" knative.yaml
  
  script:
  - gcloud builds submit --tag $IMAGE_NAME
  - gcloud run services replace --platform managed --region=$REGION knative.yaml # $APP_NAME --image $IMAGE_NAME --region=$REGION
    # --platform managed --allow-unauthenticated
  - gcloud run services set-iam-policy $APP_NAME policy.yaml


sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
