image: google/cloud-sdk:latest

variables:
  DEV_PROJECT: jsc-chatbot
  DEV_REGION:  us-central1
  DEV_APP: zkdoer-zeauth-dev


# Production build
dev_build&deploy:
  # when to run
  only:
    refs:
      - dev

  environment:
    name: production
    url: https://console.cloud.google.com/gcr/images/aifeed?project=aifeed

  before_script:
    - cat $JSC_CHATBOT_SA > jsc-chatbot-sa.json

  script:
    - gcloud run deploy $DEV_APP --project $DEV_PROJECT --region $DEV_REGION --source .