image: google/cloud-sdk:latest

variables:
  DEV_PROJECT: jsc-chatbot
  DEV_REGION:  us-central1
  DEV_APP: zkdoer-zeauth-dev

# dev build
dev_build_deploy:
  # when to run
  only:
    refs:
      - devhttps://www.figma.com/file/xjBrDvt1aB5SINl8mTuD7B/DOHA-NEWS-PROJECT?node-id=63%3A702

  environment:
    name: production
    url: https://console.cloud.google.com/gcr/images/aifeed?project=aifeed

  before_script:
    - echo $JSC_CHATBOT_SA > jsc-chatbot-sa.json
    - echo $DEV_GOOGLE_APPLICATIONS_CREDENTIALS > google-sa.json
    - ls
    - export GOOGLE_APPLICATIONS_CREDENTIALS=$PWD/google-sa.json
    - gcloud auth activate-service-account --key-file google-sa.json # Activate your service account
    - gcloud auth configure-docker # Configure docker environment
    - gcloud config set project $DEV_PROJECT #Set the GCP Project ID to the variable name
  script:
    - gcloud builds submit --tag gcr.io/$DEV_PROJECT/$DEV_APP #Run the gcloud build command to build our image
    - gcloud run deploy $DEV_APP --image gcr.io/$DEV_PROJECT/$DEV_APP --region=$DEV_REGION --platform managed --allow-unauthenticated # Run the gcloud run deploy command to deploy our new service
