# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - build
  - test

image: google/cloud-sdk:latest
variables:
  PROVIDER: zekoder
  APP: zeauth
  DEV_PROJECT: zekoder-dev-349809
  DEV_REGION: us-central1


build dev:
  stage: .post
  only:
    refs:
    - dev
  environment:
    name: dev
    url: https://zekoder.com/dev
    
  before_script:
  - echo $ZEKODER_SA > google-sa.json
  - ls
  - export GOOGLE_APPLICATIONS_CREDENTIALS=$PWD/google-sa.json
  - gcloud auth activate-service-account --key-file google-sa.json
  - gcloud auth configure-docker
  - gcloud config set project $DEV_PROJECT

  script:
  - gcloud builds submit --tag gcr.io/$DEV_PROJECT/$PROVIDER/$APP
  # - gcloud run deploy $DEV_APP --image gcr.io/$DEV_PROJECT/$DEV_APP --region=$DEV_REGION
    # --platform managed --allow-unauthenticated


sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
