apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: SERVICE
  annotations:
    run.googleapis.com/launch-stage: BETA

spec:
  template:
    spec:
      containers:
      - image: IMAGE
        startupProbe:
                httpGet:
                  path: /
                initialDelaySeconds: 30
                periodSeconds: 60
                failureThreshold: 3
        env:
          - name: AUTH_PROVIDER
            value: "FUSIONAUTH"
          - name: applicationId
            value: "ac5329b8-9cd7-49ce-b69c-74b697003c6b"
          - name: FUSIONAUTH_APIKEY
            value: "33678980-8dbf-4b5c-8f87-d7f258c6a5a1"
          - name: ZEAUTH_URL
            value: "https://accounts.dev.zekoder.net"
          - name: FRONTEND_REDIRECT_URL
            value: "https://zekoder.netlify.app/auth/verifysociallogin"
          - name: GOOGLE_REDIRECT_URL
            value: "https://zekoder-zeauth-dev-25ahf2meja-uc.a.run.app/brokers/google/callback"
          - name: TWITTER_REDIRECT_URL
            value: "https://zekoder-zeauth-dev-25ahf2meja-uc.a.run.app/brokers/twitter/callback"
          - name: FACEBOOK_REDIRECT_URL
            value: "https://zekoder-zeauth-dev-25ahf2meja-uc.a.run.app/brokers/facebook/callback"
          - name: FACEBOOK_APP_ID
            value: "1272065640312998"
          - name: FACEBOOK_CLIENT_SECRET
            value: "062df86471eb2ce4b5115db066d353d1"
          - name: TWITTER_CONSUMER_KEY
            value: "zKi87gEmUiSMvWjqel2v3JXfK"
          - name: TWITTER_CONSUMER_SECRET
            value: "qD6QJgeOmN3Rzoecwc1qJxPjjBmsbHlj3RAtGtZqdDTZClU8kY"
          - name: GOOGLE_APP_ID
            value: "912565291875-mbrtsbtuvr9ve145br6lfj17gh0t6cv4.apps.googleusercontent.com"
          - name: GOOGLE_CLIENT_SECRET
            value: "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"
          - name: identityProviderIdGoogle
            value: "82339786-3dff-42a6-aac6-1f1ceecb6c46"
          - name: identityProviderIdFaceBook
            value: "56abdcc7-8bd9-4321-9621-4e9bbebae494"
          - name: identityProviderIdTwitter
            value: "45bb233c-0901-4236-b5ca-ac46e2e0a5a5"
          - name: KEYCLOAK_URL
            value: "https://accounts.dev.zekoder.com"
          - name: CLIENT_ID
            value: "account"
          - name: REALM_NAME
            value: "zeauth-dev"
          - name: SECRET
            value: "IFZ0A3tbaPupK78KCX3sXe5Ykx59MpKX"
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: UPPERCASE
            value: "1"
          - name: DIGITS
            value: "1"
          - name: LENGTH
            value: "12"
          - name: SPECIAL_CHARACTERS
            value: "0"
          - name: API_VERSION
            value: "0.1"
          - name: API_KEY
            value: "AIzaSyAvo2Ih4JAQaiTUCJGglcQaWR8IncIkdVk"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_HOST
            value: "34.68.146.199"
          - name: REDIS_PASSWORD
            value: "pyG91wKKQX"
          - name: MAIL_FROM
            value: "noreply@zekoder.net"
          - name: MAIL_PASSWORD
            value: "BNbJK7xOWByxwHX4k3d1di/gjaVv9qaQr2XkTV5kKYZW"
          - name: MAIL_PORT
            value: "587"
          - name: MAIL_SERVER
            value: "email-smtp.eu-central-1.amazonaws.com"
          - name: MAIL_USERNAME
            value: "AKIAWA3RKI66PIK3AQSO"
          - name: MAX_LIST_USERS
            value: "500"
          - name: JWT_SECRET_KEY
            value: "/B?D(G+KbPeShVmYq3t6w9z$C&F)H@Mc"
          - name: STR_ENCRYPT_DECRYPT_KEY
            value: "ANpYasKKpHA3D9JNTNtntJhL03W3ttzC8YT2OuyQa7A="
          - name: DB_USERNAME
            value: "postgres"
          - name: DB_PASSWORD
            value: "N6nyFiMkPb"
          - name: DB_HOST
            value: "35.184.231.146"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "zekoder"
          - name: REDIS_KEY_PREFIX
            value: "zekoder"
          - name: REDIS_CLIENT_KEY_PREFIX
            value: "zekoder-client"
          - name: ACCESS_TOKEN_EXPIRY_MINUTES
            value: "60"
          - name: REFRESH_TOKEN_EXPIRY_MINUTES
            value: "60"
          - name: REFRESH_CLIENT_TOKEN_EXPIRY_MINUTES
            value: "60"
          - name: CLIENT_TOKEN_EXPIRY_MINUTES
            value: "30"
          - name: DEFAULT_ADMIN_EMAIL
            value: "zekoder-zeauth@zekoder.net"
          - name: DEFAULT_ADMIN_PASSWORD
            value: "Zekoder@123!"
          - name: DATA_ENCRYPTION_PUB_KEY
            value: 'LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JR0pBb0dCQU5iOFdJOGYxbC9SNHI0cmhBUk02UjdQUHQ2OXZFOHV4a2JaSHhIL1ptSHhhK2xsQUpXYWM3cWcKTkJLUzJpT0xCOGNzUjJydmM0WDJ4aDdoWnBtVUJQS3VPei91aFB3bUdDS29ubWVHYkpnVE1sc3hMTFRIU042dwpiR1pILy9FL29BUDhJUzNMTTJzb2hlS1VlZUlIQzd5emhmM2pHWmd3MTdVcGxRRVZnK01aQWdNQkFBRT0KLS0tLS1FTkQgUlNBIFBVQkxJQyBLRVktLS0tLQo='
          - name: DATA_ENCRYPTION_PRIV_KEY
            value: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWXdJQkFBS0JnUURXL0ZpUEg5WmYwZUsrSzRRRVRPa2V6ejdldmJ4UExzWkcyUjhSLzJaaDhXdnBaUUNWCm1uTzZvRFFTa3Rvaml3ZkhMRWRxNzNPRjlzWWU0V2FabEFUeXJqcy83b1Q4SmhnaXFKNW5obXlZRXpKYk1TeTAKeDBqZXNHeG1SLy94UDZBRC9DRXR5ek5yS0lYaWxIbmlCd3U4czRYOTR4bVlNTmUxS1pVQkZZUGpHUUlEQVFBQgpBb0dCQU5ZUGg0SmpPZ3BJcXhPZHNxS3hqZ0ZlYkFSUE9ieENINjBWcmFrMis5T1VGbFhiZXR4N1lMWTNwQUhHCmRTdWsySWJLSVFacURFWWNkQ0wxWFZEeXoxRnJJQ1B5b0pwaGFUQ0xmMm8rR20vRjkrMUFwclR5S2RyL0I2bXMKdXVzWHFpWHBNcG92TXVLbDJpOGI4S0lyaXB3Qk9jcGxpSHo1T3hqaHQ3b2s3OUU5QWtVQTZxYmlZNFNsQ3ZxMwpTRjZXc0V4NFI4U2xDMm5uaDlOWDd1ZCtiaGRMMGUvcTBxdldOV3JVVW9BOXluQzVDSGJlSWhQWWFiUnZzTlRvClBQMXpPNGE4eU1IU0hPTUNQUURxaTI0ejJqdDZUV3BnN3lYK0FOSWxmTi9LbzZoSmo1K0I3Uy8rQms4anVNSkEKZ0E0MTNtMDNZNjIrVGdERldwUzNJWWhmcjBQbFkrdmgzTk1DUlFDcHB3VHhQTnJ5NkRnUmk4blpKMENqYXVxRgpLUW1yNjBLZFNTUGd4dGticlNHVE5ZZ0hVUGkzdVY1emVqSmRpMHVwU2IzakZ3RFYwZWtqQjRBRDNyT3BWbkRxClR3STlBSm5tVWJLT2dUYVlNN1JWVisyYXBrblk3Wk91M1k4ZlFiL2tYZmhtTldtd0l5NWxtRzE2Zk5tNmUxZ0QKSVBoZW5uU24rUzhuOXZvL0habC81d0pGQUtNVCt4RU9wY2V3UGFpaHhGeStiSGJpNkt3ZmZzWURLVU1NeW84MwpzU1RwL0MzREJuUTdHNEtjK2FHZFZ1YmU2b1QrZE9iRWtWazFEM3FJNjhPcHhlOVF0WmkwCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=='
          - name: RESET_PASSWORD_URL
            value: "https://zekoder.netlify.app/auth/resetpassword"
          - name: RESEND_CONFIRMATION_EMAIL_URL
            value: "https://zekoder.netlify.app/auth/confirm-email"